name: time_project_prod

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: TimeProjectDb
      POSTGRES_USER: tp_admin
      POSTGRES_PASSWORD: kI2eGQtDgQbf1alu3W46
    ports:
      - "5433:5432"
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tp_admin -d TimeProjectDb" ]
      interval: 30s
      timeout: 10s
      retries: 3

  apis:
    image: time_project_api
    container_name: api
    build:
      context: .
      dockerfile: TimeProject.APIs/Dockerfile
    ports:
      - 5055:8080
      - 5056:8081
    environment:
      - ConnectionStrings__PostgresConnection=Host=database;Port=5433;Database=TimeProjectDb;User Id=tp_admin;Password=kI2eGQtDgQbf1alu3W46;
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
